import { ImageSourcePropType } from 'react-native';

export const FLAGS: Record<string, ImageSourcePropType> = {
  USA: require('@assets/flags/us.png'),
  MEX: require('@assets/flags/mx.png'),
  ZAF: require('@assets/flags/za.png'),
  URU: require('@assets/flags/uy.png'),
  ARG: require('@assets/flags/ar.png'),
  PER: require('@assets/flags/pe.png'),
  CAN: require('@assets/flags/ca.png'),
  MAR: require('@assets/flags/ma.png'),
  BRA: require('@assets/flags/br.png'),
  COL: require('@assets/flags/co.png'),
  JPN: require('@assets/flags/jp.png'),
  SRB: require('@assets/flags/rs.png'),
  FRA: require('@assets/flags/fr.png'),
  AUS: require('@assets/flags/au.png'),
  TUN: require('@assets/flags/tn.png'),
  DEN: require('@assets/flags/dk.png'),
  ESP: require('@assets/flags/es.png'),
  NED: require('@assets/flags/nl.png'),
  ECU: require('@assets/flags/ec.png'),
  KOR: require('@assets/flags/kr.png'),
  GER: require('@assets/flags/de.png'),
  CRO: require('@assets/flags/hr.png'),
  IRN: require('@assets/flags/ir.png'),
  GHA: require('@assets/flags/gh.png'),
  ENG: require('@assets/flags/gb-eng.png'),
  POR: require('@assets/flags/pt.png'),
  SEN: require('@assets/flags/sn.png'),
  POL: require('@assets/flags/pl.png'),
  BEL: require('@assets/flags/be.png'),
  SUI: require('@assets/flags/ch.png'),
  CMR: require('@assets/flags/cm.png'),
  KSA: require('@assets/flags/sa.png'),
};
